### ISSUE TITLE
be nice to apache / avoid the tragedy of commons

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/github-reusable-workflows#39]
### Reproduction steps

The Jenkins security-scan reusable workflow downloads maven for every run.
this will hit a community maintained resource and is not nice.

https://en.wikipedia.org/wiki/Tragedy_of_the_commons

Just as we use our own mirror for maven artifacts we should be nicer to Apache for downloading maven (and presumable eclipse when downloading java)

### Expected Results

we do not hit apache servers every time the workflow runs

### Actual Results

we hit apache servers every time the workflow runs

### Anything else?

this can also cause some issues e.g. -> https://github.com/jenkinsci/oic-auth-plugin/actions/runs/11518246235/job/32064586667

**Comment by jtnord** [comment]
https://github.com/actions/toolkit/tree/main/packages/tool-cache to do this in an action, or switch to https://github.com/marketplace/actions/setup-maven which IIUC already does this.

**Comment by jglick** [comment]
> switch to https://github.com/marketplace/actions/setup-maven

No, see #36.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows might be the easiest approach.

I wondered if we could download via HTTP, which would be cheaper for the server (since we validate the checksum anyway), but this does not work at least for the main download site (did not check mirrors)

```console
$ curl -IL http://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
HTTP/1.1 301 Moved Permanently
Date: Fri, 25 Oct 2024 17:48:55 GMT
Server: Apache
Location: https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Fri, 25 Oct 2024 17:48:55 GMT
Server: Apache
Last-Modified: Sat, 17 Aug 2024 18:44:55 GMT
ETag: "8ae661-61fe578da5420"
Accept-Ranges: bytes
Content-Length: 9102945
Access-Control-Allow-Origin: *
Content-Type: application/x-gzip

```

**Comment by jglick** [comment]
Or we could use e.g. `https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip`; not sure about relative scalability. Or does Jenkins Artifactory still mirror Central? If so, we could use that.

**Comment by jtnord** [comment]
> No, see #36.

what particularly in there - there is nothing about this that i can see it is all reffering to setup-java? 

it mentions setup-java picks up some old maven version but I am taking about setup-\*maven\* which allows you to specify the maven version and uses the github tool-cache to avoid hammering systems (somehow).

**Comment by jtnord** [comment]
I think I may have also filed this against the wrong repo (although the same issue may well apply) I meant to file it against [jenkins-security-scan](https://github.com/jenkins-infra/jenkins-security-scan/blob/main/.github/workflows/jenkins-security-scan.yaml) but it appears that is a cut and paste of this anyway.

**Comment by jtnord** [comment]
> > No, see #36.
> 
> what particularly in there - there is nothing about this that i can see it is all reffering to setup-java?
> 
> it mentions setup-java picks up some old maven version but I am taking about setup-*maven* which allows you to specify the maven version and uses the github tool-cache to avoid hammering systems (somehow).

e.g. (untested)

```yaml
  release:
    runs-on: ubuntu-latest
    needs: [validate]
    if: needs.validate.outputs.should_release == 'true'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
```

**Comment by jglick** [comment]
> I am taking about setup-*maven* which allows you to specify the maven version

https://github.com/jenkins-infra/github-reusable-workflows/issues/36#issuecomment-2383881689

**Comment by olamy** [comment]
> Or we could use e.g. `https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip`; not sure about relative scalability. Or does Jenkins Artifactory still mirror Central? If so, we could use that.


the scalability of `https://repo.maven.apache.org/` is the same as Maven central as it's just a CNAME over Maven Central.
Bear in mind it's the default url for mvnw (Maven Wrapper) and the default url of `central` in Apache Maven distribution so I would not be scared about scalability.
BTW this what is used by the GHA stCarolas see https://github.com/stCarolas/setup-maven/blob/d6af6abeda15e98926a57b5aa970a96bb37f97d1/src/installer.ts#L36

another solution could to use `mvnw` instead of `mvn` (but this will probably more changes in multiple places)
First step running (as GHA nodes include some default mvn):
```
mvn org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper -Dmaven=3.9.9
```

Now it's possible to `mvnw`.
The wrapper will download the version to `~/.m2/wrapper`
BTW it would be good to setup some cache
```
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'
```

Or manually to even cache the distribution:
(not tested)
```
- name: Cache local Maven repository
  uses: actions/cache@v4
  with:
    path: ~/.m2/  (or at least ~/.m2/repository that's what done by actions/setup-java when using cache) 
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-
```
